# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Ruter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  app-name: "ruter-api"
  rg-name: "ruter-api-test-rg"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: List current directory
      run: ls
    - name: Publish
      run: dotnet publish RuterApi/RuterApi.csproj -c release -o ./publish
    - name: current directory
      run: |
            pwd
            ls 
    - name: Upload a Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ruterApi
        path: ./publish
        if-no-files-found: error
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: STAGING
      url: ${{ steps.deploywebapp.outputs.webapp-url }}

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: ruterApi
        path: ./artifact
    - name: Current directory
      run: |
            pwd
            ls 
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Ruter Api to Azure
      id: deployRuterApi
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app-name }}
        package: ruterApi

    - name: az cli logout
      run: az logout
