# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Ruter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: List current directory
      run: ls
    - name: Publish
      run: dotnet publish RuterApi/RuterApi.csproj -c release -o Artifacts/api
    - name: current directory
      run: |
            pwd
            ls
    - name: Upload a Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        path: Artifacts/**
        if-no-files-found: error
